# Global seed
seed: 0

# Datamodule configuration to initialize a LightningDataModule
data_module_type: "cifar10:cat"
# syntax: data_module_type: "cifar" - load the all dataset
# syntax data_module_type: "cifar10:cat" - load dataset with specific category
data_module:
  data_dir: "./_datasets/"
  batch_size: 16
  num_workers: 2
  image_size: 32
  # augmentations
  random_horizontal_flip: false

# Module Config (model, scheduler and optimizer)
module:
  model:
    num_heads: 0 # A value of 0 implies scaled dot-product attention instead of multihead attention.
    image_size: ${data_module.image_size}  # Use a reference to data_module.image_size
    activation: "relu"

  optimizer:
    learning_rate: 2e-4

# lightning.Trainer Config
trainer:
  limit_train_batches: 1.0
  limit_test_batches: 1.0
  limit_val_batches: 1.0
  max_epochs: 10
  log_every_n_steps: 10
