# Global seed
seed: 0

# Datamodule configuration to initialize a LightningDataModule
data_module_type: "cifar10"
# syntax: data_module_type: "cifar" - load the all dataset
# syntax data_module_type: "cifar10:cat" - load dataset with specific category
data_module:
  data_dir: "./_datasets/"
  batch_size: 16
  num_workers: 2
  image_size: 32
  # augmentations
  random_horizontal_flip: true

# Logger Configs
tensor_board_logger:
  save_dir: "./_logging"
  name: "diffuser"
  version: null

# Model storage
best_models_dir: "./_best_models/diffusion"
export_onnx: True
export_safetensors: True

# Module Config (model, scheduler and optimizer)
module:
  model:
    in_channels: 3
    out_channels: 3
    time_dim: 256
    num_heads: 0 # A value of 0 implies scaled dot-product attention instead of multihead attention.
    widths: [32, 64, 128, 256]
    attentions: [True, True, True]
    image_size: ${data_module.image_size}  # Use a reference to data_module.image_size.
    activation: "relu"

  scheduler:
    scheduler_type: "ddpm"
    num_steps: 1000
    beta_start: 1e-4
    beta_end: 2e-2
    beta_schedule: "linear"

  optimizer:
    learning_rate: 1e-4
    prediction_type: "noise" # noise/sample/v-prediction

# Training Configs
earlystopping: False

# lightning.Trainer Config
trainer:
  limit_train_batches: 1.0
  limit_test_batches: 1.0
  limit_val_batches: 1.0
  max_epochs: 100
  log_every_n_steps: 10
