# Global seed
seed: 0

# Datamodule configuration to initialize a LightningDataModule
data_module_type: "cifar10:cat"
# syntax: data_module_type: "cifar" - load the all dataset
# syntax data_module_type: "cifar10:cat" - load dataset with specific category
data_module:
  data_dir: "./datasets/"
  batch_size: 16
  num_workers: 2
  image_size: 32
  # augmentations
  random_horizontal_flip: false

# Logger Configs
tensor_board_logger:
  save_dir: "./experiments"
  name: "gan"
  version: null

# Export model
export_onnx: True
export_safetensors: True


# Module Config (model, scheduler and optimizer)
module_type: "gan"
module:
  model:
    image_size: ${data_module.image_size}  # Use a reference to data_module.image_size
    in_channels: 3
    num_classes: 10
    image_embedding: 100
    class_embedding: 16

  optimizer:
    learning_rate: 1e-4

# Training Configs
earlystopping: False

# lightning.Trainer Config
trainer:
  # fast_dev_run: 1
  limit_train_batches: 1.0
  limit_test_batches: 1.0
  limit_val_batches: 1.0
  max_epochs: 20
  log_every_n_steps: 10
