# Global seed
seed: 0

# Datamodule configuration to initialize a LightningDataModule
data_module_type: "cifar10"
# syntax: data_module_type: "cifar" - load the all dataset
# syntax data_module_type: "cifar10:cat" - load dataset with specific category
data_module:
  data_dir: "./_datasets/"
  batch_size: 16
  num_workers: 2
  image_size: 32
  # augmentations
  random_horizontal_flip: true

# Module Config (model, scheduler and optimizer)
module:
  model:
    time_dim: 256
    num_heads: 0 # A value of 0 implies scaled dot-product attention instead of multihead attention.
    image_size: ${data_module.image_size}  # Use a reference to data_module.image_size
    activation: "relu"

  scheduler:
    scheduler_type: "ddpm"
    num_steps: 1000
    beta_start: 1e-5
    beta_end: 1e-2
    beta_schedule: "linear"

  optimizer:
    learning_rate: 1e-4
    prediction_type: "noise" # noise/sample/v-prediction

# lightning.Trainer Config
trainer:
  fast_dev_run: 1
