seed: 0

data_module:
  _target_: wiskers.datasets.cifar10_subset.CIFAR10Subset
  data_dir: "./datasets/"
  batch_size: 16
  num_workers: 2
  image_size: 32
  category_name: "cat"
  # augmentations
  random_horizontal_flip: true
