seed: 0

data_module:
  _target_: wiskers.datasets.clevrer.ClevrerVideo
  data_dir: "./datasets"
  batch_size: 4
  num_workers: 2
  chunk_size: 16
  stride: 16
  resize: [160, 240]
  image_size: [80, 120]
