# Global seed
seed: 0

# Datamodule configuration to initialize a LightningDataModule
data_module_type: "clevrer"
# syntax: data_module_type: "cifar" - load the all dataset
# syntax data_module_type: "cifar10:cat" - load dataset with specific category
data_module:
  data_dir: "./datasets"
  batch_size: 4
  num_workers: 2
  chunk_size: 16
  stride: 16
  resize: [240, 160] 
