# This is a basic workflow to check formatting
name: Ruff Action

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API, or on push events.
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      # Run Ruff and update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .

